# Generated by Django 4.2.13 on 2024-06-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Technical Issue', 'Technical Issue'), ('Give Feedback', 'Give Feedback')], default='General Inquiry', max_length=20),
        ),
    ]
